### ISSUE TITLE
DHL Express: No rates returned within EU

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#347]
Within karrio, the DHL Express carrier does not return any services/rates for shipping within the EU (e.g. from DE to DE or DE to NL). We can only test in test mode at the moment, as DHL Express has not approved productive XML access yet.

The request to DHL Express is successful (`<ActionStatus>Success</ActionStatus>`).
Version: 2023.1.12.01

This is a full example request sent by Karrio:
```
<p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd " schemaVersion="2.0">
    <GetQuote>
        <Request>
            <ServiceHeader>
                <MessageTime>2023-03-21T11:37:44</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
                <Password>xxxxx</Password>
            </ServiceHeader>
            <MetaData>
                <SoftwareName>3PV</SoftwareName>
                <SoftwareVersion>1.0</SoftwareVersion>
            </MetaData>
        </Request>
        <From>
            <CountryCode>DE</CountryCode>
            <Postalcode>76131</Postalcode>
            <City>Karlsruhe</City>
        </From>
        <BkgDetails>
            <PaymentCountryCode>DE</PaymentCountryCode>
            <Date>2023-03-21</Date>
            <ReadyTime>PT11H37M</ReadyTime>
            <DimensionUnit>CM</DimensionUnit>
            <WeightUnit>KG</WeightUnit>
            <NumberOfPieces>1</NumberOfPieces>
            <ShipmentWeight>1</ShipmentWeight>
            <Pieces>
                <Piece>
                    <PieceID>1</PieceID>
                    <Height>18.2</Height>
                    <Depth>10</Depth>
                    <Width>33.7</Width>
                    <Weight>1</Weight>
                </Piece>
            </Pieces>
            <PaymentAccountNumber>144061389</PaymentAccountNumber>
            <IsDutiable>Y</IsDutiable>
            <NetworkTypeCode>AL</NetworkTypeCode>
            <QtdShp>
                <GlobalProductCode>P</GlobalProductCode>
                <LocalProductCode>P</LocalProductCode>
                <QtdShpExChrg>
                    <SpecialServiceType>WY</SpecialServiceType>
                </QtdShpExChrg>
            </QtdShp>
        </BkgDetails>
        <To>
            <CountryCode>NL</CountryCode>
            <Postalcode>5642 JJ</Postalcode>
            <City>Eindhoven</City>
        </To>
        <Dutiable>
            <DeclaredCurrency>EUR</DeclaredCurrency>
            <DeclaredValue>1.</DeclaredValue>
        </Dutiable>
    </GetQuote>
</p:DCTRequest>
```

See also:
- Docs https://xmlportal.dhl.com/shared
- SDK https://xmlportal.dhl.com/XMLPI_Toolkit

**Comment by danh91** [comment]
Hi @MarcoWel ,

Do you have a log of the DHL response that was returned?

**Comment by MarcoWel** [comment]
Sure. This is the full response of aforementioned request:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<res:DCTResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com DCT-Response.xsd'>
    <GetQuoteResponse>
        <Response>
            <ServiceHeader>
                <MessageTime>2023-03-21T11:37:45.257+00:00</MessageTime>
                <MessageReference>xxxxxx</MessageReference>
                <SiteID>xxxxxx</SiteID>
            </ServiceHeader>
        </Response>
        <Note>
            <ActionStatus>Success</ActionStatus>
        </Note>
    </GetQuoteResponse>
</res:DCTResponse>
<!-- ServiceInvocationId:20230321113745_52d4_45513969-8cad-491b-9df1-ed3ca7264d13 -->
```

**Comment by MarcoWel** [comment]
@danh91 Please reopen this issue, it remains with 2023.3. Any idea? :)

**DHL Express Sandbox with shipment from DE to DE:**
```
<p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd " schemaVersion="2.0">
    <GetQuote>
        <Request>
            <ServiceHeader>
                <MessageTime>2023-03-27T15:14:59</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
                <Password>xxxxx</Password>
            </ServiceHeader>
            <MetaData>
                <SoftwareName>3PV</SoftwareName>
                <SoftwareVersion>1.0</SoftwareVersion>
            </MetaData>
        </Request>
        <From>
            <CountryCode>DE</CountryCode>
            <Postalcode>76131</Postalcode>
            <City>Karlsruhe</City>
        </From>
        <BkgDetails>
            <PaymentCountryCode>DE</PaymentCountryCode>
            <Date>2023-03-27</Date>
            <ReadyTime>PT15H14M</ReadyTime>
            <DimensionUnit>CM</DimensionUnit>
            <WeightUnit>KG</WeightUnit>
            <NumberOfPieces>1</NumberOfPieces>
            <ShipmentWeight>1</ShipmentWeight>
            <Pieces>
                <Piece>
                    <PieceID>1</PieceID>
                    <Height>18.2</Height>
                    <Depth>10</Depth>
                    <Width>33.7</Width>
                    <Weight>1</Weight>
                </Piece>
            </Pieces>
            <PaymentAccountNumber>xxxxx</PaymentAccountNumber>
            <IsDutiable>Y</IsDutiable>
            <NetworkTypeCode>AL</NetworkTypeCode>
        </BkgDetails>
        <To>
            <CountryCode>DE</CountryCode>
            <Postalcode>76646</Postalcode>
            <City>Bruchsal</City>
        </To>
        <Dutiable>
            <DeclaredCurrency>EUR</DeclaredCurrency>
            <DeclaredValue>1.</DeclaredValue>
        </Dutiable>
    </GetQuote>
</p:DCTRequest>
```

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<res:DCTResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com DCT-Response.xsd'>
    <GetQuoteResponse>
        <Response>
            <ServiceHeader>
                <MessageTime>2023-03-27T15:14:59.370+00:00</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
            </ServiceHeader>
        </Response>
        <Note>
            <ActionStatus>Success</ActionStatus>
            <Condition>
                <ConditionCode>410301</ConditionCode>
                <ConditionData>Products not available between this origin and destination (network segment)</ConditionData>
            </Condition>
        </Note>
    </GetQuoteResponse>
</res:DCTResponse>
```

**DHL Express Sandbox with shipment from DE to NL:**
```
<p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd " schemaVersion="2.0">
    <GetQuote>
        <Request>
            <ServiceHeader>
                <MessageTime>2023-03-27T15:15:17</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
                <Password>xxxxx</Password>
            </ServiceHeader>
            <MetaData>
                <SoftwareName>3PV</SoftwareName>
                <SoftwareVersion>1.0</SoftwareVersion>
            </MetaData>
        </Request>
        <From>
            <CountryCode>DE</CountryCode>
            <Postalcode>76131</Postalcode>
            <City>Karlsruhe</City>
        </From>
        <BkgDetails>
            <PaymentCountryCode>DE</PaymentCountryCode>
            <Date>2023-03-27</Date>
            <ReadyTime>PT15H15M</ReadyTime>
            <DimensionUnit>CM</DimensionUnit>
            <WeightUnit>KG</WeightUnit>
            <NumberOfPieces>1</NumberOfPieces>
            <ShipmentWeight>1</ShipmentWeight>
            <Pieces>
                <Piece>
                    <PieceID>1</PieceID>
                    <Height>18.2</Height>
                    <Depth>10</Depth>
                    <Width>33.7</Width>
                    <Weight>1</Weight>
                </Piece>
            </Pieces>
            <PaymentAccountNumber>xxxxx</PaymentAccountNumber>
            <IsDutiable>Y</IsDutiable>
            <NetworkTypeCode>AL</NetworkTypeCode>
            <QtdShp>
                <GlobalProductCode>P</GlobalProductCode>
                <LocalProductCode>P</LocalProductCode>
                <QtdShpExChrg>
                    <SpecialServiceType>WY</SpecialServiceType>
                </QtdShpExChrg>
            </QtdShp>
        </BkgDetails>
        <To>
            <CountryCode>NL</CountryCode>
            <Postalcode>5642 JJ</Postalcode>
            <City>Eindhoven</City>
        </To>
        <Dutiable>
            <DeclaredCurrency>EUR</DeclaredCurrency>
            <DeclaredValue>1.</DeclaredValue>
        </Dutiable>
    </GetQuote>
</p:DCTRequest>
```

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<res:DCTResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com DCT-Response.xsd'>
    <GetQuoteResponse>
        <Response>
            <ServiceHeader>
                <MessageTime>2023-03-27T15:15:18.189+00:00</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
            </ServiceHeader>
        </Response>
        <Note>
            <ActionStatus>Success</ActionStatus>
        </Note>
    </GetQuoteResponse>
</res:DCTResponse>
```

**Comment by MarcoWel** [comment]
Just tried sending the request via Postman. It leads to the same result.

However, if I remove the PLT data block (_QtdShp_) and set _IsDutiable_ to _N_, it now returns rates within the EU. Problem solved!
```
<p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd " schemaVersion="2.0">
    <GetQuote>
        <Request>
            <ServiceHeader>
                <MessageTime>2023-03-27T15:15:17</MessageTime>
                <MessageReference>xxxxx</MessageReference>
                <SiteID>xxxxx</SiteID>
                <Password>xxxxx</Password>
            </ServiceHeader>
            <MetaData>
                <SoftwareName>3PV</SoftwareName>
                <SoftwareVersion>1.0</SoftwareVersion>
            </MetaData>
        </Request>
        <From>
            <CountryCode>DE</CountryCode>
            <Postalcode>76131</Postalcode>
            <City>Karlsruhe</City>
        </From>
        <BkgDetails>
            <PaymentCountryCode>DE</PaymentCountryCode>
            <Date>2023-03-27</Date>
            <ReadyTime>PT15H15M</ReadyTime>
            <DimensionUnit>CM</DimensionUnit>
            <WeightUnit>KG</WeightUnit>
            <NumberOfPieces>1</NumberOfPieces>
            <ShipmentWeight>1</ShipmentWeight>
            <Pieces>
                <Piece>
                    <PieceID>1</PieceID>
                    <Height>18.2</Height>
                    <Depth>10</Depth>
                    <Width>33.7</Width>
                    <Weight>1</Weight>
                </Piece>
            </Pieces>
            <PaymentAccountNumber>xxxxx</PaymentAccountNumber>
            <IsDutiable>N</IsDutiable>
            <NetworkTypeCode>AL</NetworkTypeCode>
        </BkgDetails>
        <To>
            <CountryCode>NL</CountryCode>
            <Postalcode>5642 JJ</Postalcode>
            <City>Eindhoven</City>
        </To>
        <Dutiable>
            <DeclaredCurrency>EUR</DeclaredCurrency>
            <DeclaredValue>1.</DeclaredValue>
        </Dutiable>
    </GetQuote>
</p:DCTRequest>
```

![image](https://user-images.githubusercontent.com/80592577/228197339-93b6465d-93db-44a7-b626-0ad7b340fb23.png)

**Comment by danh91** [comment]
This should be fixed by https://github.com/karrioapi/karrio/pull/355

**Comment by MarcoWel** [comment]
@danh91 Unfortunately still not working.

**DE --> NL:** Rate showing up now, but getting an error when attempting to actually create the label. Seems the _Dutiable_ block is not complete. As shipments within EU are not dutiable most of the time (there are exceptions), a quick fix would be to set _IsDutiable_ to N:
```
karrio.api        | DEBUG serializable.py 21 <req:ShipmentRequest xsi:schemaLocation="http://www.dhl.com ship-val-global-req.xsd" xmlns:req="http://www.dhl.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="10.0">
karrio.api        |     <Request>
karrio.api        |         <ServiceHeader>
karrio.api        |             <MessageTime>2023-03-31T14:32:54</MessageTime>
karrio.api        |             <MessageReference>xxxxx</MessageReference>
karrio.api        |             <SiteID>xxxxx</SiteID>
karrio.api        |             <Password>xxxxx</Password>
karrio.api        |         </ServiceHeader>
karrio.api        |         <MetaData>
karrio.api        |             <SoftwareName>3PV</SoftwareName>
karrio.api        |             <SoftwareVersion>10.0</SoftwareVersion>
karrio.api        |         </MetaData>
karrio.api        |     </Request>
karrio.api        |     <RegionCode>EU</RegionCode>
karrio.api        |     <LanguageCode>en</LanguageCode>
karrio.api        |     <Billing>
karrio.api        |         <ShipperAccountNumber>xxxxx</ShipperAccountNumber>
karrio.api        |         <ShippingPaymentType>S</ShippingPaymentType>
karrio.api        |     </Billing>
karrio.api        |     <Consignee>
karrio.api        |         <CompanyName>xxxxx</CompanyName>
karrio.api        |         <AddressLine1>xxxxx</AddressLine1>
karrio.api        |         <City>Eindhoven</City>
karrio.api        |         <PostalCode>5642 JJ</PostalCode>
karrio.api        |         <CountryCode>NL</CountryCode>
karrio.api        |         <CountryName>Netherlands</CountryName>
karrio.api        |         <Contact>
karrio.api        |             <PersonName>xxxxx</PersonName>
karrio.api        |             <PhoneNumber>0000</PhoneNumber>
karrio.api        |         </Contact>
karrio.api        |     </Consignee>
karrio.api        |     <Dutiable>
karrio.api        |         <DeclaredValue>1</DeclaredValue>
karrio.api        |         <DeclaredCurrency>USD</DeclaredCurrency>
karrio.api        |     </Dutiable>
karrio.api        |     <UseDHLInvoice>Y</UseDHLInvoice>
karrio.api        |     <DHLInvoiceType>PFI</DHLInvoiceType>
karrio.api        |     <ExportDeclaration>
karrio.api        |         <InvoiceNumber>0000000</InvoiceNumber>
karrio.api        |         <InvoiceDate>2023-03-31</InvoiceDate>
karrio.api        |         <BillToCompanyName>xxxxx</BillToCompanyName>
karrio.api        |         <BillToContactName>xxxxx</BillToContactName>
karrio.api        |         <BillToAddressLine1>xxxxx</BillToAddressLine1>
karrio.api        |         <BillToAddressLine2>xxxxx</BillToAddressLine2>
karrio.api        |         <BillToCity>Karlsruhe</BillToCity>
karrio.api        |         <BillToPostcode>76131</BillToPostcode>
karrio.api        |         <BillToCountryCode>DE</BillToCountryCode>
karrio.api        |         <BillToCountryName>Germany</BillToCountryName>
karrio.api        |         <BillToPhoneNumber>xxxxx</BillToPhoneNumber>
karrio.api        |         <PlaceOfIncoterm>N/A</PlaceOfIncoterm>
karrio.api        |         <ShipmentPurpose>PERSONAL</ShipmentPurpose>
karrio.api        |     </ExportDeclaration>
karrio.api        |     <ShipmentDetails>
karrio.api        |         <Pieces>
karrio.api        |             <Piece>
karrio.api        |                 <PieceID>1</PieceID>
karrio.api        |                 <PackageType>YP</PackageType>
karrio.api        |                 <Weight>1</Weight>
karrio.api        |                 <Width>33</Width>
karrio.api        |                 <Height>18</Height>
karrio.api        |                 <Depth>10</Depth>
karrio.api        |                 <PieceReference>
karrio.api        |                     <ReferenceID>xxxxx</ReferenceID>
karrio.api        |                 </PieceReference>
karrio.api        |             </Piece>
karrio.api        |         </Pieces>
karrio.api        |         <WeightUnit>K</WeightUnit>
karrio.api        |         <GlobalProductCode>P</GlobalProductCode>
karrio.api        |         <LocalProductCode>P</LocalProductCode>
karrio.api        |         <Date>2023-03-31</Date>
karrio.api        |         <Contents>N/A</Contents>
karrio.api        |         <DimensionUnit>C</DimensionUnit>
karrio.api        |         <PackageType>YP</PackageType>
karrio.api        |         <IsDutiable>Y</IsDutiable>
karrio.api        |         <CurrencyCode>USD</CurrencyCode>
karrio.api        |     </ShipmentDetails>
karrio.api        |     <Shipper>
karrio.api        |         <ShipperID>xxxxx</ShipperID>
karrio.api        |         <CompanyName>xxxxx</CompanyName>
karrio.api        |         <RegisteredAccount>xxxxx</RegisteredAccount>
karrio.api        |         <AddressLine1>xxxxx</AddressLine1>
karrio.api        |         <AddressLine2>xxxxx</AddressLine2>
karrio.api        |         <City>Karlsruhe</City>
karrio.api        |         <PostalCode>76131</PostalCode>
karrio.api        |         <CountryCode>DE</CountryCode>
karrio.api        |         <CountryName>Germany</CountryName>
karrio.api        |         <Contact>
karrio.api        |             <PersonName>xxxxx</PersonName>
karrio.api        |             <PhoneNumber>xxxxx</PhoneNumber>
karrio.api        |             <Email>xxxxx</Email>
karrio.api        |         </Contact>
karrio.api        |     </Shipper>
karrio.api        |     <SpecialService>
karrio.api        |         <SpecialServiceType>WY</SpecialServiceType>
karrio.api        |     </SpecialService>
karrio.api        |     <LabelImageFormat>PDF</LabelImageFormat>
karrio.api        |     <Label>
karrio.api        |         <LabelTemplate>6X4_PDF</LabelTemplate>
karrio.api        |     </Label>
karrio.api        | </req:ShipmentRequest>
karrio.api        | 
karrio.api        | DEBUG helpers.py 209 sending request (5038325a-e36a-45e9-ac9e-fac9b8bcf401)...
karrio.api        | INFO helpers.py 150 Request URL:: https://xmlpitest-ea.dhl.com/XMLShippingServlet
karrio.api        | DEBUG serializable.py 36 <?xml version="1.0" encoding="UTF-8"?><res:ErrorResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com err-res.xsd'>
karrio.api        |     <Response>
karrio.api        |         <ServiceHeader>
karrio.api        |             <MessageTime>2023-03-31T14:32:54.123+00:00</MessageTime>
karrio.api        |             <MessageReference>xxxxx</MessageReference>
karrio.api        |             <SiteID>xxxxx</SiteID>
karrio.api        |         </ServiceHeader>
karrio.api        |         <Status>
karrio.api        |             <ActionStatus>Error</ActionStatus>
karrio.api        |             <Condition>
karrio.api        |                 <ConditionCode>111</ConditionCode>
karrio.api        |                 <ConditionData>Error in parsing request XML:Error: The content of element type &quot;Dutiable&quot; is
karrio.api        |                     incomplete, it must match
karrio.api        |                     &quot;(DeclaredValue?,DeclaredCurrency,ScheduleB?,ExportLicense?,ShipperEIN?,ShipperIDType?,ConsigneeIDType?,ImportLicense?,ConsigneeEIN?,TermsOfTrade,CommerceLicensed?,Filing?,SellerEIN?,SellerIDType?,SellerIDIssuingCountryCode?)&quot;.
karrio.api        |                     at line 35, column 17</ConditionData>
karrio.api        |             </Condition>
karrio.api        |         </Status>
karrio.api        |     </Response></res:ErrorResponse>
```

**DE --> DE:** No rate showing up, getting the following error straight away. Seems you did not change _IsDutiable_ to N for domestic shipments (when from_country == to_country):
```
karrio.api        | DEBUG serializable.py 21 <p:DCTRequest xmlns:p="http://www.dhl.com" xmlns:p1="http://www.dhl.com/datatypes" xmlns:p2="http://www.dhl.com/DCTRequestdatatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dhl.com DCT-req.xsd" schemaVersion="2.0">
karrio.api        |     <GetQuote>
karrio.api        |         <Request>
karrio.api        |             <ServiceHeader>
karrio.api        |                 <MessageTime>2023-03-31T14:35:59</MessageTime>
karrio.api        |                 <MessageReference>xxxxx</MessageReference>
karrio.api        |                 <SiteID>xxxxx</SiteID>
karrio.api        |                 <Password>xxxxx</Password>
karrio.api        |             </ServiceHeader>
karrio.api        |             <MetaData>
karrio.api        |                 <SoftwareName>3PV</SoftwareName>
karrio.api        |                 <SoftwareVersion>1.0</SoftwareVersion>
karrio.api        |             </MetaData>
karrio.api        |         </Request>
karrio.api        |         <From>
karrio.api        |             <CountryCode>DE</CountryCode>
karrio.api        |             <Postalcode>76131</Postalcode>
karrio.api        |             <City>Karlsruhe</City>
karrio.api        |         </From>
karrio.api        |         <BkgDetails>
karrio.api        |             <PaymentCountryCode>DE</PaymentCountryCode>
karrio.api        |             <Date>2023-03-31</Date>
karrio.api        |             <ReadyTime>PT14H35M</ReadyTime>
karrio.api        |             <DimensionUnit>CM</DimensionUnit>
karrio.api        |             <WeightUnit>KG</WeightUnit>
karrio.api        |             <NumberOfPieces>1</NumberOfPieces>
karrio.api        |             <ShipmentWeight>1</ShipmentWeight>
karrio.api        |             <Pieces>
karrio.api        |                 <Piece>
karrio.api        |                     <PieceID>1</PieceID>
karrio.api        |                     <Height>18.2</Height>
karrio.api        |                     <Depth>10</Depth>
karrio.api        |                     <Width>33.7</Width>
karrio.api        |                     <Weight>1</Weight>
karrio.api        |                 </Piece>
karrio.api        |             </Pieces>
karrio.api        |             <PaymentAccountNumber>144061389</PaymentAccountNumber>
karrio.api        |             <IsDutiable>Y</IsDutiable>
karrio.api        |             <NetworkTypeCode>AL</NetworkTypeCode>
karrio.api        |             <QtdShp/>
karrio.api        |         </BkgDetails>
karrio.api        |         <To>
karrio.api        |             <CountryCode>DE</CountryCode>
karrio.api        |             <Postalcode>76646</Postalcode>
karrio.api        |             <City>Bruchsal</City>
karrio.api        |         </To>
karrio.api        |         <Dutiable>
karrio.api        |             <DeclaredCurrency>EUR</DeclaredCurrency>
karrio.api        |             <DeclaredValue>1.</DeclaredValue>
karrio.api        |         </Dutiable>
karrio.api        |     </GetQuote>
karrio.api        | </p:DCTRequest>
karrio.api        | 
karrio.api        | DEBUG helpers.py 209 sending request (5b7c8cc1-e31b-4156-87b2-8974164abaa6)...
karrio.api        | INFO helpers.py 150 Request URL:: https://xmlpitest-ea.dhl.com/XMLShippingServlet
karrio.api        | DEBUG serializable.py 36 <?xml version="1.0" encoding="UTF-8" standalone="no"?><res:DCTResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com DCT-Response.xsd'>
karrio.api        |     <GetQuoteResponse>
karrio.api        |         <Response>
karrio.api        |             <ServiceHeader>
karrio.api        |                 <MessageTime>2023-03-31T14:35:59.719+00:00</MessageTime>
karrio.api        |                 <MessageReference>xxxxx</MessageReference>
karrio.api        |                 <SiteID>xxxxx</SiteID>
karrio.api        |             </ServiceHeader>
karrio.api        |         </Response>
karrio.api        |         <Note>
karrio.api        |             <ActionStatus>Success</ActionStatus>
karrio.api        |             <Condition>
karrio.api        |                 <ConditionCode>410301</ConditionCode>
karrio.api        |                 <ConditionData>Products not available between this origin and destination (network segment)</ConditionData>
karrio.api        |             </Condition>
karrio.api        |         </Note>
karrio.api        |     </GetQuoteResponse></res:DCTResponse>
```
